# Generated by Django 5.1.6 on 2025-02-15 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill_rate_system', '0002_project_status_timesheet_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='status',
        ),
    ]
